# Search all PMs for this token to process:
token_regex: "HOPE(?:_?16|2025)[VP]?T?-[0-9A-F]{8}-(?:[0-9A-F]{4}-){3}[0-9A-F]{9,10}"
# The URL format for talk links, capturing the shortcode
schedule_talk_regex: "https://scheduler.hope.net/foo/talk/([a-z0-9]{5,})/"
# Strongly recommended to set to false in prod
enable_token_clearing: false
rooms:
  # Where tokens will join people
  attendee: "!foo:host.tld"
  volunteer: "!foo:host.tld"
  presenter: "!foo:host.tld"
  press: "!foo:host.tld"
  # Space for the talk rooms
  talks: '!foo:host.tld'
  # Where should announcements go?
  announcements: '!foo:host.tld'
  # Where should !mod flags go?
  moderation: '!foo:host.tld'
# Said for help command, new PM rooms, or PMs not containing a token
help: >-
  Hello! I'm the HOPE core bot. To gain access to the HOPE
  chat rooms, just send me the token you were sent by email.
  It looks like this: `HOPE16-EBC92A72-9151-885B-5526-FBE8D5A37F`
# Allowed to use bot admin commands and given admin perms in talk chats
owners:
  - "@bar:host.tld"
# Shortcodes for talks that don't deserve chat rooms
talk_chat_skip:
  - 'NSLJQ9'
talk_chat_moderators:
  - "@foo:host.tld"
# Set talk chat message/react/redact permissions to 50 (moderator+)
talk_chats_locked: false
pretalx_json_url: "https://scheduler.hope.net/foo/schedule.json"
# Roughly: seconds delay per request for intensive processes
ratelimit_multiplier: 2
timezone: America/New_York
